# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d72eec9287aac3e1d4012ee15a67f21724ff22b88ecf22c5da5697bd9ff7dff2ec08fb6a9e4cf7605a70a901b588730b4c34c57cf4330ee13111d521ed4270ba

test:
  secret_key_base: 82421b11901a21a941a54033d1fdc0db9ce7b5a38ba701acfb644ac73d70aa71c8447159c1131bb7469f620eb7f775b879cd9c457b579e28b4678e909ae45734

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
